settings:
    index:
        # single node, no sharding
        number_of_shards: 1
        number_of_replicas: 0
mappings:
    dynamic: false # disable dynamic mapping
    properties:
          title: &en_text
              type: text
              analyzer: french
          author: *en_text
          content: *en_text
          #createdAt:
              #type: date
              #format: yyyy-MM-dd HH:mm:ss